#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# (c) 2021-2023, Konstantin Demin

##tag tree/etc/custom

set -f

rm="rm -rf${VERBOSE:+v}"
[ -z "${DEBUG}" ] || set -xv

xglob /etc /usr/local/etc/container/cleanup/etc -- ${rm} </dev/null
exit 0
