#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# (c) 2021-2023, Konstantin Demin

##tag var/cron

set -f

rm="rm -f${VERBOSE:+v}"
[ -z "${DEBUG}" ] || set -xv

xglob /var /usr/local/etc/cleanup/cron-var -- ${rm} </dev/null
exit 0
