#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# (c) 2021-2023, Konstantin Demin

##tag var/run

set -f

[ -z "${DEBUG}" ] || set -xv

find /run/ -mindepth 1 ${VERBOSE:+-ls} -delete

set -e
cd /run

install -d -m 01777 \
	lock \
	screen \
	user \

exit 0
