#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# (c) 2021-2023, Konstantin Demin

##tag var/machine-id

set -ef

rm="rm -f${VERBOSE:+v}"
[ -z "${DEBUG}" ] || set -xv

${rm} /var/lib/dbus/machine-id

echo uninitialized > /etc/machine-id
