#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# (c) 2021-2023, Konstantin Demin

set -ef

w=$(mktemp -d) ; : "${w:?}"

apt-list-installed > "$w/all"

f='/var/lib/apt/extended_states'
if [ -f "$f" ] ; then
	mawk '
	/^Package:/,/^$/ {
		if ($1 == "Package:")        { pkg = $2; }
		if ($1 == "Architecture:")   { arch = $2; }
		if ($1 == "Auto-Installed:") { is_auto = $2; }
		if ($0 == "") {
			if (is_auto == 1) { print pkg ":" arch; }
		}
	}
	' "$f" | sort -V
fi > "$w/auto.pkg"

while : ; do
	[ -s "$w/auto.pkg" ] || break

	# fix:
	# /var/lib/apt/extended_states stores (some) arch:all entries as arch:native
	sed -En '/^([^:]+):all$/ {s##/^\1:.+$/ {s//\1:all/}#p}' \
	< "$w/all" \
	> "$w/auto.sed"

	if [ -s "$w/auto.sed" ] ; then
		sed -E -f "$w/auto.sed"
	else
		cat
	fi < "$w/auto.pkg"

	break
done

rm -rf "$w"
