#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# (c) 2018-2023, Konstantin Demin

set -ef

# $1 - ephemeral name
# $2 - apt repo uri
# $3 - distribution
# $4 - first component
: "${1:?}" "${2:?}" "${3:?}" "${4:?}"

name="$1"
uri="$2"
distro="$3"
shift 3

printf 'deb-src %s %s %s\n' "${uri}" "${distro}" "$*" >> "/etc/apt/sources.list.d/${name}.list"
