#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# (c) 2023, Konstantin Demin

set -ef

src_file='/etc/apt/sources.list.d/backports.list'

if [ $# = 0 ] ; then
	if [ -s "${src_file}" ] ; then
		echo '# backports are enabled'
	else
		echo '# backports are disabled'
	fi >&2
	exit 0
fi

act=$(echo "$1" | tr '[:upper:]' '[:lower:]')
case "${act}" in
status)
	[ -s "${src_file}" ]
	exit
;;
enable|enable-all)
	. /etc/os-release
	mawk 'NR==1{$3="'"${VERSION_CODENAME}"'-backports";print $0;}' \
	< /etc/apt/sources.list \
	> "${src_file}"
;;
disable|disable-all)
	rm -f "${src_file}"
;;
*)
	env printf '# unknown apt-backports action: %q\n' "$1" >&2
	exit 1
;;
esac

case "${act}" in
enable-all)
	apt-pin backports 500 "${VERSION_CODENAME}-backports" '*'
;;
disable-all)
	apt-pin backports rm
;;
esac
