#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# (c) 2022-2023, Konstantin Demin

set -f

[ $# -ne 0 ] || {
	echo "# ${0##*/}: no command was specified" 1>&2
	exit 1
}

t=$(mktemp)
if [ -z "$t" ] ; then
	echo "# ${0##*/}: unable to create temporary file" 1>&2

	# unable to create temporary file?
	# no output in case of error
	exec "$@" </dev/null >/dev/null 2>/dev/null
fi

( "$@" ; ) </dev/null >"$t" 2>"$t"

r=$?
if [ $r != 0 ] ; then
	printf '# command:'
	env printf ' %q' "$@"
	echo
	echo "# return code: $r"
	if [ -s "$t" ] ; then
		echo '# output:'
		sed -E 's/^(.+)$/#>| \1/;s/^$/#=|/' < "$t"
	fi
fi 1>&2

rm -f "$t"
exit $r
