#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# (c) 2021-2023, Konstantin Demin

##tag apt/custom

set -f

rm="rm -rf${VERBOSE:+v}"
[ -z "${DEBUG}" ] || set -xv

xglob / /usr/local/etc/cleanup/apt -- ${rm} </dev/null
exit 0
