#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# (c) 2021-2023, Konstantin Demin

##tag apt/logs

set -ef

rm="rm -f${VERBOSE:+v}"
[ -z "${DEBUG}" ] || set -xv

xglob /var/log -- ${rm} <<-'EOF'
	match=apt/*.log
	match=apt/*.log.*
	match=aptitude
	match=aptitude.*
EOF
