#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# (c) 2021-2023, Konstantin Demin

##tag dpkg/custom

set -f

rm="rm -rf${VERBOSE:+v}"
[ -z "${DEBUG}" ] || set -xv

xglob / - "${CLEANUP_CONF_DIR:?}/dpkg" -- ${rm} <<-'EOF'
	match=/etc/dpkg/dpkg.cfg.d/docker*
	match=/etc/dpkg/dpkg.cfg.d/excludes
EOF
