#!/bin/sh

set -e

if [ "$1" != "upgrade" ]; then
	python_bin=/@{PYTHON_PREFIX}/bin
	lib=/@{PYTHON_MODULES}

	for suffix in '' '-@{PYTHON_BASE_VERSION}' '@{PYTHON_MAJOR_VERSION}' '@{PYTHON_BASE_VERSION}' ; do
		update-alternatives --remove \
		  python${suffix} \
		  ${python_bin}/python
	done

	# remove precompiled Python bytecode
	find ${lib}/ -name __pycache__ -type d -exec rm -rf '{}' '+'
	find ${lib}/ -name '*.py[co]' -ls -delete
fi

#DEBHELPER#

exit 0
