#!/bin/sh

set -e

case "$1" in
configure)
	prio=$(( @{DEB_PYTHON_PRIO} + 1 ))
	bin=/usr/bin
	pkgcfg=/usr/lib/@{DEB_HOST_MULTIARCH}/pkgconfig

	for suffix in '' '@{PYTHON_MAJOR_VERSION}' ; do
		stem=python${suffix}

		update-alternatives --install \
		  ${bin}/@{DEB_HOST_MULTIARCH}-${stem}-config \
		  @{DEB_HOST_MULTIARCH}-${stem}-config \
		  ${bin}/@{DEB_HOST_MULTIARCH}-python@{PYTHON_BASE_VERSION}-config \
		${prio} \


		update-alternatives --install \
		  ${bin}/${stem}-config \
		  ${stem}-config \
		  ${bin}/@{DEB_HOST_MULTIARCH}-python@{PYTHON_BASE_VERSION}-config \
		${prio} \
		--slave \
		  ${pkgcfg}/${stem}.pc \
		  ${stem}.pc-@{DEB_HOST_MULTIARCH} \
		  ${pkgcfg}/python-@{PYTHON_BASE_VERSION}.pc \
		--slave \
		  ${pkgcfg}/${stem}-embed.pc \
		  ${stem}-embed.pc-@{DEB_HOST_MULTIARCH} \
		  ${pkgcfg}/python-@{PYTHON_BASE_VERSION}-embed.pc \


	done
;;
abort-upgrade|abort-remove|abort-deconfigure)
;;
*)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
;;
esac

#DEBHELPER#

exit 0
