#!/bin/sh

set -e

if [ "$1" != "upgrade" ]; then
	python_bin=/@{PYTHON_PREFIX}/bin

	for suffix in '' '@{PYTHON_MAJOR_VERSION}' '@{PYTHON_BASE_VERSION}' ; do
		stem=python${suffix}

		update-alternatives --remove \
		  ${stem}-config \
		  ${python_bin}/python-config
	done

	update-alternatives --remove \
	  python-config-@{PYTHON_BASE_VERSION} \
	  ${python_bin}/python-config
fi

#DEBHELPER#

exit 0
