#!/bin/sh

set -e

case "$1" in
configure)
	prio=$(( @{DEB_PYTHON_PRIO} + 1 ))
	bin=/usr/bin
	python_bin=/@{PYTHON_PREFIX}/bin
	pkgcfg=/usr/lib/@{DEB_HOST_MULTIARCH}/pkgconfig
	python_pkgcfg=/@{PYTHON_PREFIX}/lib/pkgconfig

	for suffix in '' '@{PYTHON_MAJOR_VERSION}' '@{PYTHON_BASE_VERSION}' ; do
		stem=python${suffix}

		update-alternatives --install \
		  ${bin}/${stem}-config \
		  ${stem}-config \
		  ${python_bin}/python-config \
		${prio} \
		--slave \
		  ${bin}/@{DEB_HOST_MULTIARCH}-${stem}-config \
		  @{DEB_HOST_MULTIARCH}-${stem}-config \
		  ${python_bin}/python-config \
		--slave \
		  ${pkgcfg}/${stem}.pc \
		  ${stem}.pc-@{DEB_HOST_MULTIARCH} \
		  ${python_pkgcfg}/python-@{PYTHON_BASE_VERSION}.pc \
		--slave \
		  ${pkgcfg}/${stem}-embed.pc \
		  ${stem}-embed.pc-@{DEB_HOST_MULTIARCH} \
		  ${python_pkgcfg}/python-@{PYTHON_BASE_VERSION}-embed.pc \

	done

	update-alternatives --install \
	  ${bin}/python-config-@{PYTHON_BASE_VERSION} \
	  python-config-@{PYTHON_BASE_VERSION} \
	  ${python_bin}/python-config \
	${prio} \
;;
abort-upgrade|abort-remove|abort-deconfigure)
;;
*)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
;;
esac

#DEBHELPER#

exit 0
