#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# (c) 2021-2023, Konstantin Demin

set -ef

want_y=1
for i ; do
    case "$i" in
    -y* | -q*y*) want_y= ;;
    esac
done

apt-update ${APT_OPTS}
apt-env apt-get ${want_y:+ -y } ${APT_OPTS} ${APT_METHOD:-install} "$@"
