#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# (c) 2021-2023, Konstantin Demin

##tag var/cron

set -f

rm="rm -f${VERBOSE:+v}"
[ -z "${DEBUG}" ] || set -xv

xglob /var "${CLEANUP_CONF_DIR:?}/cron-var" -- ${rm} </dev/null
exit 0
