#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# (c) 2021-2023, Konstantin Demin

##tag dpkg/debconf
# remove i18n from (debconf) templates

set -f

rm="rm -f${VERBOSE:+v}"
[ -z "${DEBUG}" ] || set -xv

debconf-trim-i18n /var/cache/debconf/templates.dat

find "${DPKG_ADMINDIR:-/var/lib/dpkg}/info/" -name '*.templates' \
  -exec debconf-trim-i18n '{}' '+'

xglob /var/cache/debconf -- ${rm} <<-EOF
	match=*-old
EOF

exit 0
