#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# (c) 2021-2023, Konstantin Demin

##tag dpkg/filter
# post-install file system filtering instead of slowing down installations

set -f

rule_stanza='^(delete|keep)=(.+)$'
reformat_xglob='s/^delete/match/;s/^keep/skip/'

rm="rm -f${VERBOSE:+v}"
[ -z "${DEBUG}" ] || set -xv

# : "${DPKG_ADMINDIR:=/var/lib/dpkg}"

# work directory
w=$(mktemp -d) ; : "${w:?}"

_cleanup() {
	cd /
	rm -rf -- "$w"
}

# NB: executable files in this directory are considered to be "skipped"
find -L /usr/local/etc/dpkg-filter/ -type f ! -executable \
  -exec grep -hE "${rule_stanza}" '{}' '+' \
> "$w/rules.raw"

sort -uV < "$w/rules.raw" > "$w/rules"
rm -f "$w/rules.raw"

# nothing to match at all
if ! [ -s "$w/rules" ] ; then
	_cleanup
	exit 0
fi

sed -E "${reformat_xglob}" "$w/rules" > "$w/rules.xglob"
xglob / "$w/rules.xglob" -- printf '%s\0' > "$w/list"

# nothing to filter at all
if ! [ -s "$w/list" ] ; then
	_cleanup
	exit 0
fi

# remove files immediately
xargs -r -0 ${rm} < "$w/list"

# TODO: deal with diversions?

_cleanup
exit 0
