#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# (c) 2021-2023, Konstantin Demin

##tag dpkg/filter
# post-install file system filtering instead of slowing down installations

set -f

[ -z "${DEBUG}" ] || set -xv

# NB: executable files in this directory are considered to be "skipped"
find -L /usr/local/etc/dpkg-filter/ -type f ! -executable \
  -exec dpkg-filter '{}' '+'

exit 0
