#!/bin/sh

set -ef

wrapper=/@{NODEJS_PREFIX}/share/thin-ci.sh

if [ "$1" != "upgrade" ]; then
	for suffix in '' '-@{NODEJS_MAJOR_VERSION}' ; do
		update-alternatives --remove \
		  nodejs${suffix} \
		  ${wrapper}

		for i in npm yarn ; do
			update-alternatives --remove \
			  $i${suffix} \
			  ${wrapper}
		done
	done

	# compatibility with Debian
	update-alternatives --remove \
	  js \
	  ${wrapper}
fi

#DEBHELPER#

exit 0
