#!/bin/sh

set -e

if [ "$1" != "upgrade" ]; then
	bin=/usr/bin

	for suffix in '' '@{PYTHON_MAJOR_VERSION}' ; do
		stem=python${suffix}

		update-alternatives --remove \
		  @{DEB_HOST_MULTIARCH}-${stem}-config \
		  ${bin}/@{DEB_HOST_MULTIARCH}-python@{PYTHON_BASE_VERSION}-config

		update-alternatives --remove \
		  ${stem}-config \
		  ${bin}/python@{PYTHON_BASE_VERSION}-config

	done
fi

#DEBHELPER#

exit 0
