#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# (c) 2021-2023, Konstantin Demin

##tag var/tmp

set -f

[ -z "${DEBUG}" ] || set -xv

find /tmp/ -mindepth 1 ${VERBOSE:+-ls} -delete

set -e
cd /tmp

for d in ICE X11 XIM font ; do
	d=".$d-unix"
	[ -d "$d" ] || install -d -m 01777 "$d"
done

exit 0
